filebeat.prospectors:
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601
#  username: kibana
#  password: kibana

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
#  username: elastic
#  password: youpassword
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
