
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-demo
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx:1.17.8
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx-demo
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 8089
      targetPort: 80
      name: nginx-demo-port
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-demo
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-demo
  endpoints:
    - port: nginx-demo-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lx1036
  labels:
    app: nginx-lx1036
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-lx1036
      labels:
        app: nginx-lx1036
    spec:
      containers:
        - name: nginx-lx1036
          image: lx1036/nginx:v1.0.0.1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx-lx1036
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lx1036
spec:
  selector:
    app: nginx-lx1036
  ports:
    - port: 8090
      targetPort: 80
      name: nginx-lx1036-port
  type: NodePort

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-lx1036
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-lx1036
  endpoints:
    - port: nginx-lx1036-port
---
